/*
  Warnings:

  - You are about to drop the column `ttl` on the `Lansia` table. All the data in the column will be lost.
  - You are about to drop the `Balita` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `IbuHamil` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `alamatKK` to the `Lansia` table without a default value. This is not possible if the table is not empty.
  - Added the required column `jenisKelamin` to the `Lansia` table without a default value. This is not possible if the table is not empty.
  - Added the required column `tanggalLahir` to the `Lansia` table without a default value. This is not possible if the table is not empty.
  - Changed the type of `bb` on the `Lansia` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.
  - Changed the type of `tb` on the `Lansia` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- AlterSequence
ALTER SEQUENCE "Lansia_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "Lansia" DROP COLUMN "ttl";
ALTER TABLE "Lansia" ADD COLUMN     "alamatKK" STRING NOT NULL;
ALTER TABLE "Lansia" ADD COLUMN     "jenisKelamin" STRING NOT NULL;
ALTER TABLE "Lansia" ADD COLUMN     "posyanduId" INT4;
ALTER TABLE "Lansia" ADD COLUMN     "tanggalLahir" DATE NOT NULL;
ALTER TABLE "Lansia" DROP COLUMN "bb";
ALTER TABLE "Lansia" ADD COLUMN     "bb" FLOAT8 NOT NULL;
ALTER TABLE "Lansia" DROP COLUMN "tb";
ALTER TABLE "Lansia" ADD COLUMN     "tb" FLOAT8 NOT NULL;

-- DropTable
DROP TABLE "Balita";

-- DropTable
DROP TABLE "IbuHamil";

-- CreateTable
CREATE TABLE "Bumil" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "nik" STRING NOT NULL,
    "kk" STRING NOT NULL,
    "tanggalLahir" DATE NOT NULL,
    "umur" INT4 NOT NULL,
    "alamat" STRING NOT NULL,
    "alamatKK" STRING NOT NULL,
    "bb" FLOAT8 NOT NULL,
    "tb" FLOAT8 NOT NULL,
    "usiaHamil" FLOAT8 NOT NULL,
    "lingkarLengan" FLOAT8 NOT NULL,
    "bpjs" STRING NOT NULL,
    "g" INT4 NOT NULL,
    "p" INT4 NOT NULL,
    "a" INT4 NOT NULL,
    "hpht" DATE NOT NULL,
    "tp" DATE NOT NULL,
    "hb" STRING NOT NULL,
    "namaSuami" STRING NOT NULL,
    "nikSuami" STRING NOT NULL,
    "tanggalLahirSuami" DATE NOT NULL,
    "posyanduId" INT4
);

-- CreateIndex
CREATE UNIQUE INDEX "Bumil_id_key" ON "Bumil"("id");

-- AddForeignKey
ALTER TABLE "Lansia" ADD CONSTRAINT "Lansia_posyanduId_fkey" FOREIGN KEY ("posyanduId") REFERENCES "Posyandu"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Bumil" ADD CONSTRAINT "Bumil_posyanduId_fkey" FOREIGN KEY ("posyanduId") REFERENCES "Posyandu"("id") ON DELETE SET NULL ON UPDATE CASCADE;
