-- CreateTable
CREATE TABLE "Posyandu" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL
);

-- CreateTable
CREATE TABLE "Admin" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "posyanduId" INT4
);

-- CreateTable
CREATE TABLE "Lansia" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- CreateTable
CREATE TABLE "IbuHamil" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- CreateTable
CREATE TABLE "Balita" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- CreateTable
CREATE TABLE "Bayi" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- CreateIndex
CREATE UNIQUE INDEX "Posyandu_id_key" ON "Posyandu"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Admin_id_key" ON "Admin"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Admin_email_key" ON "Admin"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Lansia_id_key" ON "Lansia"("id");

-- CreateIndex
CREATE UNIQUE INDEX "IbuHamil_id_key" ON "IbuHamil"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Balita_id_key" ON "Balita"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Bayi_id_key" ON "Bayi"("id");

-- AddForeignKey
ALTER TABLE "Admin" ADD CONSTRAINT "Admin_posyanduId_fkey" FOREIGN KEY ("posyanduId") REFERENCES "Posyandu"("id") ON DELETE SET NULL ON UPDATE CASCADE;
