-- CreateTable
CREATE TABLE "Posyandu" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL
);

-- CreateTable
CREATE TABLE "Admin" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "posyanduId" INT4
);

-- CreateTable
CREATE TABLE "Lansia" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "nik" STRING NOT NULL,
    "kk" STRING NOT NULL,
    "jenisKelamin" STRING NOT NULL,
    "tanggalLahir" DATE NOT NULL,
    "umur" INT4 NOT NULL,
    "alamat" STRING NOT NULL,
    "alamatKK" STRING NOT NULL,
    "bb" FLOAT8 NOT NULL,
    "tb" FLOAT8 NOT NULL,
    "tensi" STRING NOT NULL,
    "bpjs" STRING NOT NULL,
    "posyanduId" INT4
);

-- CreateTable
CREATE TABLE "Bumil" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "nik" STRING NOT NULL,
    "kk" STRING NOT NULL,
    "tanggalLahir" DATE NOT NULL,
    "umur" INT4 NOT NULL,
    "alamat" STRING NOT NULL,
    "alamatKK" STRING NOT NULL,
    "bb" FLOAT8 NOT NULL,
    "tb" FLOAT8 NOT NULL,
    "usiaHamil" FLOAT8 NOT NULL,
    "lingkarLengan" FLOAT8 NOT NULL,
    "bpjs" STRING NOT NULL,
    "g" INT4 NOT NULL,
    "p" INT4 NOT NULL,
    "a" INT4 NOT NULL,
    "hpht" DATE NOT NULL,
    "tp" DATE NOT NULL,
    "hb" STRING NOT NULL,
    "namaSuami" STRING NOT NULL,
    "nikSuami" STRING NOT NULL,
    "tanggalLahirSuami" DATE NOT NULL,
    "tempatLahirSuami" DATE NOT NULL,
    "posyanduId" INT4
);

-- CreateTable
CREATE TABLE "Bayi" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- CreateIndex
CREATE UNIQUE INDEX "Posyandu_id_key" ON "Posyandu"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Admin_id_key" ON "Admin"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Admin_email_key" ON "Admin"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Lansia_id_key" ON "Lansia"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Bumil_id_key" ON "Bumil"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Bayi_id_key" ON "Bayi"("id");

-- AddForeignKey
ALTER TABLE "Admin" ADD CONSTRAINT "Admin_posyanduId_fkey" FOREIGN KEY ("posyanduId") REFERENCES "Posyandu"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lansia" ADD CONSTRAINT "Lansia_posyanduId_fkey" FOREIGN KEY ("posyanduId") REFERENCES "Posyandu"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Bumil" ADD CONSTRAINT "Bumil_posyanduId_fkey" FOREIGN KEY ("posyanduId") REFERENCES "Posyandu"("id") ON DELETE SET NULL ON UPDATE CASCADE;
